### ISSUE TITLE
[Editor]Сохранить и загрузить в DB связку сущностей необходимых для полноценной игры

### ISSUE THREAD

**Issue by Alexander091** [Alexander091/text-adventure#15]
Наладить взаимодействие с DB сохранение/редактирование/удаление

**Comment by bogomolovd** [comment]
Добавлен скрипт testdata.sql в dao-manager-db. В скрипте добавляется квест, 4 узла и 6 переходов между ними. Также назначается стартовый узел для квеста.

**Comment by Alexander091** [comment]
Есть ещё один момент, который меня беспокоит. Настроено ли у нас рекурсивное удаление данных? Т.е удалив сущность quest из базы, удаляться ли все зависимые node и все transiton, которые зависят от node.
Проверь, пожалуйста. Если у нас такого нет, то добавь, пожалуйста.

**Comment by OctoOsmo** [comment]
Такого нет: ON UPDATE NO ACTION ON DELETE NO ACTION

**Comment by bogomolovd** [comment]
Взаимодействие с БД было налажено, теперь можно произвести цикл создания, редактирования и удаления узла.
