### ISSUE TITLE
[Editor] Добавить в UI граф для редактора квестов

### ISSUE THREAD

**Issue by Alexander091** [Alexander091/text-adventure#17]
Граф должен показывать общую структуру игры и реагировать на события: клик на узел, клик на ребро. Эти события должны быть обработаны соответствующим образом

**Comment by bogomolovd** [comment]
Граф с тестовыми данными был добавлен. (Пока без обработки событий)

**Comment by bogomolovd** [comment]
Теперь данные загружаются с rest контроллера (пока тестовые)

**Comment by bogomolovd** [comment]
граф отображает данные из базы и реагирует на клик по узлу и ребру
