### ISSUE TITLE
[Game] Реализовать структуру переходов в игре согласно диаграмме классов

### ISSUE THREAD

**Issue by Alexander091** [Alexander091/text-adventure#19]
Структура переходов, загрузка этапов игры, должна быть согласно диаграмме классов.
Реализация должна быть достаточно гибкой, чтобы можно было реализовать работу actions, transitions, inventory и т.д

**Comment by zmaks** [comment]
Выполнено, но пока у меня jsf бины взаимодействуют с entities. В ближайшее время сделаю обертку для используемых таким образом entity в impl-модуле.

**Comment by zmaks** [comment]
Добавлены обертки для используемых entites.
Задача выполнена.
