### ISSUE TITLE
[QuestsStorage]Добавить поддержку загрузки и удаления квестов из базы

### ISSUE THREAD

**Issue by Alexander091** [Alexander091/text-adventure#21]
Наладить взаимодействие через Hibernate и загружать и удалять данные из базы.
Возможно поможет скрипт из issue https://github.com/Alexander091/text-adventure/issues/16

**Comment by OctoOsmo** [comment]
#12 Реализовал загрузку квестов из базы

**Comment by OctoOsmo** [comment]
#12 Реализовал удаление квестов из компонента dataScroller

**Comment by OctoOsmo** [comment]
#12 Загрузка и удаление квестов реализованы
