### ISSUE TITLE
[QuestsStorage] Добавить поддержку выбора режима отображения квестов

### ISSUE THREAD

**Issue by Alexander091** [Alexander091/text-adventure#22]
В таблице должна быть поддержка отображения квеста списком или таблицей. Соответственно данные все должны подхватываться из JSF контроллера.
А так же добавить кнопки для удаления, редактирования, начала игры.

**Comment by OctoOsmo** [comment]
#12 Сделал выбор режима отображения с помощью PrimeFaces TabView.
Планирую заменить его другим решением.

**Comment by OctoOsmo** [comment]
Добавил кнопку изменения режима отображения
