### ISSUE TITLE
[Base] Создать шаблон сайта

### ISSUE THREAD

**Issue by Alexander091** [Alexander091/text-adventure#23]
Добавить общий шаблон, в который будут встраиваться остальные страницы. 
На этом шаблоне если нужно должны быть какие-нибудь базовые вещи вроде "регистрации", "авторизации". 
Реализация страниц для Runtime ошибок, 404 ошибок и т.д. Соответственно настроить шаблон в web.xml, чтобы осуществлялся переход на эти страницы.
Добавить пока только шаблоны страниц авторизации и регистрации

**Comment by OctoOsmo** [comment]
#12 Подключил тему PrimeFaces в text-adventure-app-web/web.xml
Добавил загрузку темы в проект с помощью maven (главный pom фвйл)

**Comment by OctoOsmo** [comment]
#12 Сделал папку с шаблонами страниц. Теперь страница может интегрироваться в него.
Сделал интеграцию для модулей quest-storage и quest-editor
