### ISSUE TITLE
[Authorization] Добавить возможность авторизации для пользователей

### ISSUE THREAD

**Issue by Alexander091** [Alexander091/text-adventure#24]
Авторизация должна (в данный момент) предоставлять админские права и открывать доступ к редактору карт. 
Давать пользователю возможность удалять/создавать/редактировать квесты.
Так же реализация должна быть достаточно гибкой, чтобы можно было добавить новые роли пользователям, которые будут отличные от админской.
Помимо всего прочего авторизация не должна быть обязательной. т.е неавторизованный пользователь может играть в квесты, но от него должны быть закрыты другие формы, на которые у него не хватает прав. 
Если пользователь совершает операцию, на которую у него не хватает прав, то система должна перенаправлять его на станицу с ошибкой, где будет говориться, что у пользователя недостаточно прав.

**Comment by OctoOsmo** [comment]
#40 Реализовано
