### ISSUE TITLE
[Editor] Реализовать uploader для ресурсов

### ISSUE THREAD

**Issue by Alexander091** [Alexander091/text-adventure#25]
Загрузчик должен загружать картинки, звуки и сохранять их на сервере, а базе хранить относительные пути на них.

При редактировании Экшена и Квеста должна быть возможность на месте выбрать подходящую картинку

**Comment by Alexander091** [comment]
Кто сейчас этим занимается? Я увидел этот класс как у Саши, так и у Димы

**Comment by OctoOsmo** [comment]
Загрузчик картинок готов.

**Comment by OctoOsmo** [comment]
Переназначил на Диму.

**Comment by bogomolovd** [comment]
загрузчик звуков готов
