### ISSUE TITLE
[Game] Добавить поддержку Actions в одиночной игре

### ISSUE THREAD

**Issue by Alexander091** [Alexander091/text-adventure#32]
Так же тут нужно продумать гибкую систему, которая позволит добавлять новые экшены без серьёзных изменений в коде
Добавить Actions в одиночную игру:
- [x] Смена фона
- [x] Проигрывание музыки

**Comment by zmaks** [comment]
Сделал actions со сменой фона. Но пока без нормального UI

**Comment by zmaks** [comment]
С музыкой разобрался тоже. В итоге, задача выполнена
