### ISSUE TITLE
[Game] Сделать GameBean stateless

### ISSUE THREAD

**Issue by Alexander091** [Alexander091/text-adventure#38]
Сейчас наблюдается ошибка с внедрением бина, если его сделать Stateless
Это нужно исправить, а также этот бин должен реализовывать локальный интерфейс и внедряться он должен через интерфейс, а не через класс

**Comment by zmaks** [comment]
Stateful bean не может быть заинжекчен в stateless, так как stateful хранится в сессии, а stateless с сессией никак не взаимодействует. Отсюда и ошибка. Есть решение этой проблемы через @Resource, но пока у меня так сделать не получилось. 
http://stackoverflow.com/questions/11437206/java-ee-6-how-to-call-stateful-session-bean-from-stateless-session-bean
